USE master;
GO
ALTER DATABASE ControlWork
ADD FILEGROUP CWS;
GO
ALTER DATABASE ControlWork
ADD FILE 
(
NAME = CWS1,
FILENAME = 'C:ControlWork\CWS1',
FILEGROWTH = 10MB
)
TO FILEGROUP CWS;
GO
ALTER DATABASE ControlWork
MODIFY FILEGROUP CW DEFAULT;
GO
ALTER DATABASE ControlWork
REMOVE FILE ControlWork_log1;
GO